// Package genhttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package genhttp

import (
	"time"
)

// Defines values for HealthStatus.
const (
	Degraded  HealthStatus = "degraded"
	Healthy   HealthStatus = "healthy"
	Unhealthy HealthStatus = "unhealthy"
)

// Defines values for LivenessResponseStatus.
const (
	Alive LivenessResponseStatus = "alive"
)

// Defines values for ReadinessResponseStatus.
const (
	NotReady ReadinessResponseStatus = "not ready"
	Ready    ReadinessResponseStatus = "ready"
)

// HealthCheck defines model for HealthCheck.
type HealthCheck struct {
	// Duration How long the check took
	Duration string `json:"duration"`

	// Message Additional message about the health status
	Message *string `json:"message,omitempty"`

	// Service Name of the service being checked
	Service string `json:"service"`

	// Status Health status of a service
	Status HealthStatus `json:"status"`

	// Timestamp When the check was performed
	Timestamp time.Time `json:"timestamp"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Checks Individual service health checks
	Checks []HealthCheck `json:"checks"`

	// Status Health status of a service
	Status HealthStatus `json:"status"`

	// Timestamp When the health check was performed
	Timestamp time.Time `json:"timestamp"`

	// Uptime Application uptime
	Uptime string `json:"uptime"`

	// Version Application version
	Version string `json:"version"`
}

// HealthStatus Health status of a service
type HealthStatus string

// LivenessResponse defines model for LivenessResponse.
type LivenessResponse struct {
	// Service Service name
	Service string `json:"service"`

	// Status Liveness status
	Status LivenessResponseStatus `json:"status"`

	// Timestamp When the check was performed
	Timestamp time.Time `json:"timestamp"`
}

// LivenessResponseStatus Liveness status
type LivenessResponseStatus string

// ReadinessResponse defines model for ReadinessResponse.
type ReadinessResponse struct {
	// Health Health status of a service
	Health HealthStatus `json:"health"`

	// Service Service name
	Service string `json:"service"`

	// Status Readiness status
	Status ReadinessResponseStatus `json:"status"`

	// Timestamp When the check was performed
	Timestamp time.Time `json:"timestamp"`
}

// ReadinessResponseStatus Readiness status
type ReadinessResponseStatus string
