apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    url: http://influxdb:8086
    access: proxy
    isDefault: true
    editable: true
    secureJsonData:
      token: my-super-secret-auth-token
    jsonData:
      httpMode: POST
      version: Flux
      organization: social-media
      defaultBucket: metrics
      tlsSkipVerify: true
