// Package genhttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package genhttp

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for StandardResponseCode.
const (
	BADREQUEST          StandardResponseCode = "BAD_REQUEST"
	CONFLICT            StandardResponseCode = "CONFLICT"
	FAILED              StandardResponseCode = "FAILED"
	FORBIDDEN           StandardResponseCode = "FORBIDDEN"
	INTERNALSERVERERROR StandardResponseCode = "INTERNAL_SERVER_ERROR"
	NOTFOUND            StandardResponseCode = "NOT_FOUND"
	SUCCESS             StandardResponseCode = "SUCCESS"
	UNAUTHORIZED        StandardResponseCode = "UNAUTHORIZED"
)

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
}

// StandardResponse defines model for StandardResponse.
type StandardResponse struct {
	Code *StandardResponseCode `json:"code,omitempty"`

	// Data Response data (varies by endpoint)
	Data       *map[string]interface{} `json:"data,omitempty"`
	Errors     *[]string               `json:"errors,omitempty"`
	Message    *string                 `json:"message,omitempty"`
	RequestId  *string                 `json:"requestId,omitempty"`
	ServerTime *time.Time              `json:"serverTime,omitempty"`
}

// StandardResponseCode defines model for StandardResponse.Code.
type StandardResponseCode string

// PostApiAccountLoginJSONRequestBody defines body for PostApiAccountLogin for application/json ContentType.
type PostApiAccountLoginJSONRequestBody = LoginRequest

// PostApiAccountRegisterJSONRequestBody defines body for PostApiAccountRegister for application/json ContentType.
type PostApiAccountRegisterJSONRequestBody = RegisterRequest
